### ISSUE TITLE
Can't reproduce your analysis

### ISSUE THREAD

**Issue by czopluoglu** [henry090/transformers#1]
Hi,

Thank you for this demo analysis. I was hoping to apply this to another problem I am working on. I just copy/paste your code to reproduce your example first before I try out the other problem. For some reason, the models do not fit. I am getting the following long error message. 

Any idea or suggestion about what I am missing. I was running this on a Kaggle notebook.

Thank you.
 

Error in py_call_impl(callable, dots$args, dots$keywords): InvalidArgumentError:  indices[6,20] = -2147483648 is not in [0, 50257)
	 [[node functional_1/tfgp_t2model_1/transformer/wte/Gather (defined at /transformers/modeling_tf_utils.py:1446) ]] [Op:__inference_train_function_40974]

Errors may have originated from an input operation.
Input Source operations connected to node functional_1/tfgp_t2model_1/transformer/wte/Gather:
 functional_1/tfgp_t2model_1/transformer/Reshape (defined at /transformers/models/gpt2/modeling_tf_gpt2.py:300)

Function call stack:
train_function

Detailed traceback: 
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/share/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)

Traceback:

1. model %>% keras::fit(tf_train, epochs = epochs, validation_data = tf_test)
2. keras::fit(., tf_train, epochs = epochs, validation_data = tf_test)
3. fit.keras.engine.training.Model(., tf_train, epochs = epochs, 
 .     validation_data = tf_test)
4. do.call(object$fit, args)
5. (structure(function (...) 
 . {
 .     dots <- py_resolve_dots(list(...))
 .     result <- py_call_impl(callable, dots$args, dots$keywords)
 .     if (convert) 
 .         result <- py_to_r(result)
 .     if (is.null(result)) 
 .         invisible(result)
 .     else result
 . }, class = c("python.builtin.method", "python.builtin.object"
 . ), py_object = <environment>))(batch_size = NULL, epochs = 2L, 
 .     verbose = 1L, callbacks = list(<environment>), validation_split = 0, 
 .     shuffle = TRUE, class_weight = NULL, sample_weight = NULL, 
 .     initial_epoch = 0L, validation_data = <environment>, x = <environment>)
6. py_call_impl(callable, dots$args, dots$keywords)

**Comment by turgut090** [comment]
Hi. Could you turn on GPU for your notebook? It causes problems when the training is on CPU

**Comment by czopluoglu** [comment]
That made it! Thank you so much again for this demo. This is incredibly helpful. I had no idea that these tools would be available through RStudio.

Kardas Azerbeycan'a selamlar.

**Comment by turgut090** [comment]
That's great!! There a lot of useful pkgs: 
1) Torch for R https://github.com/mlverse/torch
2) fastai from R (incuding transformers https://eagerai.github.io/fastai/articles/textclassification.html) easily fine-tune and etc.

Bendende Türk Kardeşlerimize Selamlar :-)

**Comment by czopluoglu** [comment]
Thank you, Turgut! 

I have another question. I realized that the model returns completely different results with different eval metrics everytime I run. So, I assume there should be a seed to be defined to get the same results. In R environment, what do you think is the best approach to define the seed for random number generation?

Would you just define it at the beginning of the sessions for the general R environment? Or, is there a way to pass the seed as an argument somewhere in the model?

**Comment by czopluoglu** [comment]
For instance, they mention a set_seed argument in this document, but I couldn't figure out at what point you pass this to the model in your R code.

Thank you, again.

https://huggingface.co/transformers/internal/trainer_utils.html?highlight=seed#transformers.set_seed

**Comment by turgut090** [comment]
I did not run set_seed, however right after this line:

```
transformer = reticulate::import('transformers')
```
you could set_seed.

**Comment by czopluoglu** [comment]
Selam Turgut kardas,

I have another question. Sorry to bother you. I am trying to understand these Bert models better, and there is a ton of info about them but they are typically in Python.

I am trying to get what they call word or sentence embeddings. Following your blog post, I get the tokens. For instance when I run the following I get the token encodings, and I understand what they mean.

```
tok <- tokenizer$encode("Alright, let's do this",max_length = 50L,truncation=T) 
tok
0.45636.6.905.18.109.42.2
```

I would also like to get word embeddings and **sequence output**. Do you know how I can do it from R?

I was reading [this post.](https://github.com/huggingface/transformers/issues/2072) In one of the responses, someone provides the following code. I did run this and the object `final_embeddings` returns a 1 x 768 vector and they call it **sequence output**.

```
from transformers import RobertaTokenizer, RobertaModel, RobertaConfig
import torch

config = RobertaConfig.from_pretrained("roberta-base")
config.output_hidden_states = True

tok = RobertaTokenizer.from_pretrained("roberta-base")
model = RobertaModel.from_pretrained("roberta-base", config=config)

sentence = torch.tensor([tok.encode("Alright, let's do this")])

output = model(sentence)
final_embeddings = output[0]
```
I am wondering how I can get the same vector for the **sequence output** following your code in R.

Thank you again.

**Comment by turgut090** [comment]
Hi, sorry for the late reply.

I am sharing a Kaggle notebook where we run the code from R. Later we move tensor to CPU and NumPy. And finally, from the NumPy to R array.
https://www.kaggle.com/henry090/notebook6c3c68b656?scriptVersionId=65044638

**Comment by czopluoglu** [comment]
Thank you so much!
